# LithiumMod Options
#
# Copyright (C) 2010  userdelroot r00t316@gmail.com (Frank C.)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# specify seperate aliases file
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


# items in /sdcard/bin will be in your path
if [ -d "$HOME/bin" ]; then
   PATH="$HOME/bin:$PATH"
fi
