# LithiumMod Options
# 
# Copyright (C) 2010  userdelroot r00t316@gmail.com (Frank C.)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# remount /system 
# sysrw = read/write
# sysro = read-only
alias sysrw="mount -o remount,rw /system && echo /system mounted read/write || echo unable to mount /system read/write"
alias sysro="mount -o remount,ro /system && echo /system mounted read-only || echo unable to mount /system read-only"

